### PR TITLE
newer conda-lock drops optional attribute

### PR DESCRIPTION
**Pull request by AlbertDeFusco**

### CODE REVIEW

**Review by mattkram — APPROVED** [review]
LGTM. Any chance of a string (p.category) coming back with whitespace or is that well-controlled?

**Comment by AlbertDeFusco** [comment]
Good question. I'll have to check

**Comment by AlbertDeFusco** [comment]
conda-lock will throw an error during `render` 

```
pydantic.error_wrappers.ValidationError: 1 validation error for Lockfile
package -> 0 -> category
  none is not an allowed value (type=type_error.none.not_allowed)
```

**Comment by mattkram** [comment]
> conda-lock will throw an error during `render` 
> 
> ```
> pydantic.error_wrappers.ValidationError: 1 validation error for Lockfile
> package -> 0 -> category
>   none is not an allowed value (type=type_error.none.not_allowed)
> ```

Okay so my guess is they've got an enum of some sort? I should look.

As long as we're confident that non-optional packages are marked as "main" I say let's merge it.

**Pull request merged**
