### PR TITLE
chore: Add new static badge linking to documentation

### LINKED ISSUE #115: Add a link or badge to README to documentation
Add a badge or quick link to the docs from the repo README.md

### PR DESCRIPTION
**Pull request by mattkram**
Closes #115

### CODE REVIEW

**Comment by mattkram** [comment]
I'm noticing that the main CI is running, even though I've updated the `paths-ignore` filter. There may be a bug in GitHub Actions: https://github.com/actions/runner/issues/2324

I'll create an issue to discuss whether we should instead use a path include filter, which I think will work.

**Comment by mattkram** [comment]
Disregard the last comment. There is no issue. Ironically, setting the ignore rules for the `main.yaml` changes the `main.yaml`, so I had to include that in the ignore rule for testing. Will revert before we merge this PR.

**Comment by AlbertDeFusco** [comment]
Is this still in draft or ready to go?

**Comment by mattkram** [comment]
I need to revert two commits. The other thing I realized is technically CI checks wouldn't pass in the future if the tests don't run (if only README is changed or something). I will make an issue for that. This one should be fine. Will revert those now.

**Review by AlbertDeFusco — APPROVED** [review]

**Pull request merged**
